accounting_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.login.urls")),
    path("sharepoint/", include("apps.requests.urls")),
    path("requests/", include("apps.internalRequests.urls")),
    path("teams/", include("apps.teams.urls")),
    path("registration/", include("apps.registration.urls")),
    path("emailContact/", include("apps.emailContact.urls")),
    path("permissions/", include("apps.permissions.urls")),
    path("forms/", include("apps.forms.urls")),
    path("notifications/", include("apps.notifications.urls")),
    path("error/", include("apps.errorHandler.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "apps.errorHandler.views.error_404_view"

apps/login/urls.py
"""
Request urls

This module defines URL patterns for the login application.
"""

from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path("", views.login_view, name="login_view"),
    path("logout/", views.login_view, name="login_view"),
    path("resetPassword/", views.reset_password_view, name="reset_password_view"),
    path(
        "resetPassword/verifyIdentity/",
        views.verify_email_reset_view,
        name="verify_email_reset_view",
    ),
    path("changePassword/", views.change_password_view, name="change_password_view"),
    path("verifyEmail/", views.verify_email_view, name="verifyEmail_view"),
]

apps/registration/urls.py
"""
Registration urls

This module defines URL patterns for the registration application.
"""

from django.urls import path
from . import views

app_name = "registration"

urlpatterns = [
    path("", views.register_view, name="register_view"),
    path("verifyEmail/", views.verify_email_view, name="verifyEmail_view"),
]

apps/login/models.py
from django.db import models

# Create your models here.

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.contrib import messages
import utils.utils as utils
import subprocess

User = get_user_model()

global random_code

def login_view(request):
    """Handles user login and session management.

    GET: Renders the login page.
    POST: Authenticates user credentials, generates and sends a verification email for account confirmation.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered login page.
        POST: Redirects to 'login:verifyEmail_view' if authentication is successful; else, renders the login page with an error message.
    """
    if request.method == "GET":
        request.session["has_logged"] = False
        request.session["has_requested_password"] = False
        if request.user.is_authenticated and request.GET.get("logout") != "true":
            if request.user.is_superuser or request.user.is_leader:
                return redirect("/sharepoint/")
            else:
                return redirect("/requests/")
        else:
            if request.GET.get("logout") == "true":
                logout(request)
            return render(request, "login.html")
    else:
        try:
            user = authenticate(
                request,
                id=request.POST["usuario"],
                password=request.POST["contrasena"],
            )

            if user is not None:
                if user.is_none:
                    return render(
                        request,
                        "login.html",
                        {
                            "message": "Usuario no autorizado. Comuníquese con el administrador."
                        },
                    )
                request.session["user_id"] = user.id

                random_code = utils.generate_random_code()
                request.session["random_code"] = random_code
                ruta_script = "apps/login/write.py"
                comando = f"python {ruta_script} {random_code}"
                subprocess.call(comando, shell=True)

                utils.send_verification_email(
                    request,
                    "Verificación de correo",
                    "Verificación de Registro Vía Sistema de Contabilidad | Universidad Icesi <contabilidad@icesi.edu.co>",
                    user.email,
                    "Hola, bienvenido al Sistema de Contabilidad de la Universidad ICESI.\n\nSu código de verificación es: "
                    + random_code
                    + "\n\nSi no ha solicitado este correo, por favor ignorelo.",
                )
                request.session["has_logged"] = True

                return redirect("login:verifyEmail_view")
            else:
                return render(
                    request,
                    "login.html",
                    {"message": "Por favor, revisa las credenciales."},
                )
        except Exception as e:
            print(e)
            return render(
                request,
                "login.html",
                {"message": "Ingrese un usuario válido."},
            )

def verify_email_view(request):
    """Handles verification after login using a verification code.

    GET: Renders the verification page.
    POST: Verifies the entered verification code and logs the user in if successful; else, displays an error message.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered verification page.
        POST: Redirects to '/sharepoint/' if verification is successful; else, renders the verification page with an error message.
    """
    context = {"form_action": "login:verifyEmail_view"}
    if request.method == "GET":
        if request.session.get("has_logged") == True:
            return render(request, "verifyEmailLog.html", context)
        else:
            if request.user.is_authenticated:
                if request.user.is_superuser or request.user.is_leader:
                    if request.user.is_superuser or request.user.is_leader:
                        return redirect("/sharepoint/")
                    else:
                        return redirect("/requests/")
                else:
                    return redirect("/requests/")
            else:
                return redirect("login:login_view")
    else:
        if request.POST["verificationCode"] == request.session.get("random_code"):
            user_id = request.session.get("user_id")
            user = User.objects.get(id=user_id)
            backend = "django.contrib.auth.backends.ModelBackend"
            user.backend = backend
            login(request, user)
            if request.user.is_superuser or request.user.is_leader:
                return redirect("/sharepoint/")
            else:
                return redirect("/requests/")
        else:
            messages.error(request, "Código de verificación incorrecto.")
            return render(request, "verifyEmailLog.html", context)


"""
Change password methods

1. reset_password_view: Request id after clicking "Forgot password?"
2. verify_email_reset_view: Verification after putting id in "Forgot password?" to verify identity
3. change_password_view: Change password after verifying identity
4. Return to login_view after changing password
"""

def reset_password_view(request):
    """Handles the request to reset the password.

    GET: Renders the reset password page.
    POST: Sends a verification email for password reset if the user exists; else, displays an error message.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered reset password page.
        POST: Redirects to 'login:verify_email_reset_view' if user exists; else, renders the reset password page with an error message.
    """
    if request.method == "GET":
        return render(request, "reset_password.html")
    else:
        id = request.POST["userId"]
        if User.objects.filter(id=id).exists():
            request.session["user_id"] = id
            random_code = utils.generate_random_code()
            ruta_script = "apps/login/write.py"
            comando = f"python {ruta_script} {random_code}"
            subprocess.call(comando, shell=True)

            request.session["random_code"] = random_code
            user = User.objects.get(id=id)
            email = user.email
            utils.send_verification_email(
                request,
                "Verificación de correo",
                "Verificación de Registro Vía Sistema de Contabilidad | Universidad Icesi <contabilidad@icesi.edu.co>",
                email,
                "Hola, se ha solicitado un cambio de contraseña.\n\nSu código de verificación es: "
                + random_code
                + "\n\nSi no ha solicitado este cambio, ignore este mensaje.",
            )
            request.session["has_requested_password"] = True
            return redirect("login:verify_email_reset_view")
        else:
            messages.error(request, "Usuario no encontrado.")
            return render(request, "reset_password.html")

def verify_email_reset_view(request):
    """Handles verification after requesting a password reset.

    GET: Renders the verification page.
    POST: Verifies the entered verification code and redirects to 'login:change_password_view' if successful; else, displays an error message.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered verification page.
        POST: Redirects to 'login:change_password_view' if verification is successful; else, renders the verification page with an error message.
    """
    context = {"form_action": "login:verify_email_reset_view"}
    if request.method == "GET":
        if request.session.get("has_requested_password") == True:
            return render(request, "verifyEmailLog.html", context)
        else:
            if request.user.is_authenticated:
                if request.user.is_superuser or request.user.is_leader:
                    return redirect("/sharepoint/")
                else:
                    return redirect("/requests/")
            else:
                return redirect("login:login_view")
    else:
        if request.POST.get("verificationCode") == request.session.get("random_code"):
            return redirect("login:change_password_view")
        else:
            messages.error(request, "Código de verificación incorrecto.")
            return render(request, "verifyEmailLog.html", context)


def change_password_view(request):
    """Handles password change after verifying identity.

    GET: Renders the change password page.
    POST: Changes the password if password criteria are met; else, displays an error message.

    Args:
        request: HttpRequest object.

    Returns:
        GET: Rendered change password page.
        POST: Redirects to 'login:login_view' if password is changed successfully; else, renders the change password page with an error message.
    """
    if request.method == "GET":
        if request.session.get("has_requested_password") == True:
            return render(request, "change_password.html")
        else:
            if request.user.is_authenticated:
                if request.user.is_superuser or request.user.is_leader:
                    return redirect("/sharepoint/")
                else:
                    return redirect("/requests/")
            else:
                return redirect("login:login_view")
    else:
        password = request.POST["password"]
        confirm_password = request.POST["confirmPassword"]
        if password == confirm_password:
            if len(password) < 8:
                messages.error(
                    request, "La contraseña debe tener al menos 8 caracteres."
                )
                return render(request, "change_password.html")
            else:

apps/login/templates/change_password.html
{% extends "auth-base.html" %}
{% load static %}
{% block title %}Cambio de Contraseña{% endblock %}

{% block content %}

<div class="card border-0 px-2 mx-auto mt-3 mb-3 shadow"
        style="background-color: #f6f7f8">
    <div class="mx-auto mb-4">
        <img src="{% static 'login/assets/logo.png' %}"
                alt="logo"
                class="img-fluid"
                width="350px"
                height="50px">
    </div>
    <h3 class="text-center fw-bold fs-2 ">Cambio de contraseña</h3>
    <div class="card-body">
        <div class="d-flex justify-content-center text-center mb-4">
            <span class="container">Por favor, ingrese su nueva contraseña.</span>
        </div>
        <form action="{% url 'login:change_password_view' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <span class="input-identifier">INGRESA LA NUEVA CONTRASEÑA</span>
                <div class="input-group flex-nowrap">
                    <div class="input-group-text">
                        <i class="fa fa-lock icon"></i>
                    </div>
                    <input type="password"
                            class="form-control"
                            id="password"
                            name="password"
                            required>
                </div>
                <span class="input-identifier">REPITE LA CONTRASEÑA</span>
                <div class="input-group flex-nowrap">
                    <div class="input-group-text">
                        <i class="fa fa-lock icon"></i>
                    </div>
                    <input type="password"
                            class="form-control"
                            id="confirmPassword"
                            name="confirmPassword"
                            required>
                </div>
            </div>
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary mt-2 mb-2">Continuar</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

apps/login/templates/email_template.html
{{message}}

apps/login/templates/login.html
{% extends "auth-base.html" %}
{% load static %}
{% block title %}Iniciar Sesión{% endblock %}

{% block content %}
<div class="card col-md-8 border-0 px-2 mx-auto mt-3 mb-3 shadow"
 style="background-color: #f6f7f8">
    <div class="mx-auto mb-3">
        <img src="{% static 'login/assets/logo.png' %}"
            alt="logo"
            class="img-fluid"
            width="350px"
            height="50px">
    </div>
    <span class="container mb-2 mt-3">
        <h3>¡Bienvenido! 👋</h3>
        Este es el sistema de monitorización para la gestión contable de la Universidad Icesi.
    </span>
    <span class="container mb-4">Inicia sesión para continuar.</span>
    <div class="container">
        <form action="/" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <span class="input-identifier">DOCUMENTO DE IDENTIFICACIÓN</span>
                <div class="input-group flex-nowrap mb-3">
                    <div class="input-group-text">
                        <i class="fa fa-user icon"></i>
                    </div>
                    <input type="text" class="form-control" id="usuario" name="usuario" required>
                </div>
                <span class="input-identifier">INGRESA TU CONTRASEÑA</span>
                <div class="input-group flex-nowrap">
                    <div class="input-group-text">
                        <i class="fa fa-lock icon"></i>
                    </div>
                    <input type="password"
                        class="form-control"
                        id="contrasena"
                        name="contrasena"
                        required>
                </div>
            </div>
            <div class="d-flex mb-3 justify-content-center">
                <button type="submit" class="btn btn-primary mt-4">INICIAR SESIÓN</button>
            </div>
        </form>
    </div>
    <div class="d-flex flex-column align-items-center">
        <a href="{% url 'registration:register_view' %}"
        class="btn btn-link text-primary text-decoration-underline">Registrarse</a>
        <a href="{% url 'login:reset_password_view' %}"
        class="btn btn-link text-primary text-decoration-underline mb-4">¿Olvidaste tu contraseña?</a>
    </div>
</div>
{% endblock %}

apps/login/templates/reset_password.html
{% extends "auth-base.html" %}
{% load static %}
{% block title %}Recuperación de Contraseña{% endblock %}

{% block content %}
    {% with title="Recuperación de contraseña" description="Por favor, ingrese su cédula para iniciar el proceso de restablecimiento de contraseña." input_label="CÉDULA" action_url="login:reset_password_view" input_id="userId" input_name="userId" %}
        {% include 'components/email_verification_component.html' %}
    {% endwith %}
{% endblock %}

apps/login/templates/verifyEmailLog.html
{% extends "auth-base.html" %}
{% load static %}
{% block title %}Verificación de Email{% endblock %}

{% block content %}
    {% with title="Verificación de email" description="Ingrese el código de verificación que enviamos al email asociado a su cuenta." action_url=form_action input_id="verificationCode" input_label="Código de verificación" input_name="verificationCode" %}
        {% include 'components/email_verification_component.html' %}
    {% endwith %}
{% endblock %}